### ISSUE TITLE
When large content is used the render area is not updated correctly

### ISSUE THREAD

**Issue by ahancock1** [wieslawsoltes/PanAndZoom#15] opened 2017-11-27 13:01 UTC
When the content is large say 3222x3222 pixels and the render area is considerably less, the contents render area is not updated correctly. I'll fork the latest branch and create a pull request later today.

**Comment by wieslawsoltes** [comment] 2017-11-27 14:53
@ahancock1 I could not reproduce this issue on my machine.

![2017-11-27_15-52-43](https://user-images.githubusercontent.com/2297442/33272671-222ff782-d38b-11e7-9211-09dedb11b7d1.gif)

**Comment by ahancock1** [comment] 2017-11-27 16:51
It seems the issue is i wasn't using a canvas. If you change that canvas to a Grid, you might see the behaviour i'm seeing which is where only a portion of the content is rendered.

**Comment by wieslawsoltes** [comment] 2017-11-28 18:15
@ahancock1 Grid layout in WPF is causing all sorts of issues. I have same control for Avalonia and works as expected.

**Comment by ahancock1** [comment] 2017-12-06 10:10
No trouble, thanks for looking into this. I settled to using Canvas in the end as i couldn't get a work around working with the Grid

**Comment by wieslawsoltes** [comment] 2017-12-06 13:42
I did try to get Grid working but WPF layout and transforms are just to unpredictable and so many special cases exists that it would take a lot of time.

**Comment by wieslawsoltes** [comment] 2018-02-18 13:28
Closing as I could not find solution.

**Closed by wieslawsoltes** 2018-02-18 13:28 UTC
